{
 "title": "Liquor Lab",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "namespace", "label": "Namespace", "query": "${namespace}" }
  ]
 },
 "panels": [
  {
   "title": "Pipeline progress",
   "type": "larona-epict-panel",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT time,count(name)-1 AS \"images_uploaded\"\nFROM images_uploaded"
    },
    {
     "rawSql": "SELECT time,count(name)-1 AS \"images_processed\"\nFROM images_processed"
    }
   ]
  },
  {
   "title": "Last 10 uploaded images",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT * FROM images_uploaded WHERE name != '' ORDER by time DESC LIMIT 10"
    }
   ]
  },
  {
   "title": "Last 10 processed images",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT time,name FROM images_processed WHERE name != '' ORDER by time DESC LIMIT 10"
    }
   ]
  },
  {
   "title": "Distribution Analysis",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  label AS metric,\n  count(label)\nFROM images_processed\nWHERE\n  $__timeFilter(time)\n  and\n  label != ''\nGROUP BY 1,2\nORDER BY $__timeGroup(time,$__interval)"
    }
   ]
  },
  {
   "title": "Images processed by model version",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 7, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  model AS metric,\n  count(model) AS \"model\"\nFROM images_processed\nWHERE\n  $__timeFilter(time)\n  and\n  model != ''\nGROUP BY 1,2\nORDER BY $__timeGroup(time,$__interval)"
    }
   ]
  }
 ]
}